Добавленно простое избранное, возможность открытия карточки по нажати…
DVPeshe/Scrum pull request #6
Opened 2023-03-24 18:34 UTC by StrayAbandoned

…ю из избранного

2023-03-24 20:03 UTC, VorobevOleg approved these changes
На первый взгляд вроде норм. Если работает, значит merge)

2023-03-25 08:00 UTC, Kashevar128 requested changes
Все ок, только нужно обязательное подправить пакеты, чтобы проект собирался после мержа

2023-03-25 15:16 UTC, Kashevar128 approved these changes
Все ок!

2023-03-25 15:17 UTC, merged

2023-03-25 22:18 UTC, DVPesh commented on favorite-service/pom.xml
> +			<groupId>ru.vinogradov.mst.market</groupId>
!

2023-03-25 22:18 UTC, DVPesh commented on pom.xml
>  	<groupId>ru.vinogradov.mst.market</groupId>
!